# Generated by Django 5.2 on 2025-05-04 21:42


from django.db import migrations

def seed_clothing(apps, schema_editor):
    ClothingItem = apps.get_model("weather4u", "ClothingItem")
    ClothingCategory = apps.get_model("weather4u", "ClothingCategory")

    data = {
        "hot": ["Shorts", "T-shirt", "Sunglasses", "Flip-flops"],
        "warm": ["Jeans", "T-shirt", "Light jacket"],
        "cool": ["Sweater", "Jeans", "Sneakers"],
        "cold": ["Coat", "Beanie", "Gloves", "Boots"],
        "rain": ["Rain jacket", "Umbrella", "Waterproof boots"],
        "snow": ["Heavy coat", "Snow boots", "Scarf"],
        "uv_high": ["Sunscreen", "Hat", "Sunglasses"],
    }

    for category_name, item_names in data.items():
        category, _ = ClothingCategory.objects.get_or_create(name=category_name)
        for item_name in item_names:
            item, _ = ClothingItem.objects.get_or_create(name=item_name)
            item.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ('weather4u', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_clothing),
    ]

