# Generated by Django 5.2 on 2025-05-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather4u', '0002_seed_clothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='activities', to='weather4u.activitycategory')),
            ],
        ),
    ]
