# Generated by Django 5.2 on 2025-05-04 22:38

from django.db import migrations

def seed_activities(apps, schema_editor):
    Activity = apps.get_model("weather4u", "Activity")
    ActivityCategory = apps.get_model("weather4u", "ActivityCategory")

    data = {
        "sunny": [
            ("Melt from the heat", 80, 100),
            ("Go rock climbing", 70, 75),
            ("Try go-karts", 75, 80),
            ("Have a picnic", 65, 85),
        ],
        "rain": [
            ("Stay inside and eat ice cream", 32, 100),
            ("Watch a movie marathon", 32, 100),
        ],
        "light_rain": [
            ("Visit a museum", 40, 85),
        ],
        "snow": [
            ("Go sledding", 25, 32),
            ("Build a snowman", 20, 35),
        ],
    }

    for category_name, activities in data.items():
        category, _ = ActivityCategory.objects.get_or_create(name=category_name)
        for name, min_temp, max_temp in activities:
            activity, _ = Activity.objects.get_or_create(name=name, min_temp=min_temp, max_temp=max_temp)
            activity.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ('weather4u', '0003_activitycategory_activity'),
    ]

    operations = [

        migrations.RunPython(seed_activities),

    ]
